
CANTIDAD POR PRESENTACIÓN	
CONSUMO POR PACIENTE	
CONSUMO POR PACIENTE SIN ERROR	

ALCANCE DE PACIENTES POR PRESENTACION	
NECESIDAD PARA PROYECTO	PEDIDO TOTAL DEL PROYECTO 	
REMANENTE DE PEDIDO 	
PACIENTES EXTRAS	
EXISTENCIA NETA ALMACEN	
UNIDADES TOTALES EN ALMACÉN	
UNIDADES ADQUIRIDAS NO INGRESADAS	
COMPRA TOTAL 	
PRECIO UNITARIO CON IVA	
COSTO UNITARIO POR PRUEBA	
COSTO TOTAL PEDIDO	
COSTO DIRECTO DEL PROYECTO 	
COSTO TOTAL RERMANENTE	

